# ComfyUI Docker Compose File v1.0.1 by John Aldred
# http://www.johnaldred.com
# http://github.com/kaouthia

services:
  comfyk:
    build:
      dockerfile: Dockerfile
    image: comfyui:latest
    container_name: comfyui
    ports:
      - "8188:8188"
    # network_mode: "host"
    volumes:
      # persist your models, output, and settings:
      - c:/home/user/comfyui/models:/app/ComfyUI/models

      # persist your output images:
      - c:/home/user/comfyui/output:/app/ComfyUI/output
      
      # persist all your settings & extra nodes:
      - c:/home/user/comfyui/settings:/app/ComfyUI/user/default:rw

      # persist just your saved flows (overrides the workflows/ in default):
      - c:/home/user/comfyui/flows:/app/ComfyUI/user/default/workflows:rw
    
    runtime: nvidia
    environment:
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - NVIDIA_VISIBLE_DEVICES=all
    stdin_open: true
    tty: true
    restart: unless-stopped
